adding image needed for aws tests
jetstack/testing pull request #539
Opened 2021-07-30 12:42 UTC by RinkiyaKeDad

Signed-off-by: Arsh Sharma <arshsharma461@gmail.com>

Based on @irbekrm's suggestion here https://github.com/jetstack/testing/pull/512#discussion_r679861495, this PR adds the image we need to run the AWS tests.

2021-07-30 12:42 UTC, RinkiyaKeDad commented
/assign @jakexks @irbekrm

2021-07-30 12:55 UTC, irbekrm requested changes
Looks good to me! I've added two nits and a suggestion to parameterize the Go version and tag the image with that.

2021-07-30 12:55 UTC, irbekrm commented on images/golang-aws/Dockerfile
> +    ln -s /go/bin/bazelisk /usr/local/bin/bazel;
Nit: new line

2021-07-30 12:55 UTC, irbekrm commented on images/golang-aws/build.yaml
> +- ${_REGISTRY}/${_NAME}:latest
Nit: new line

2021-07-30 12:55 UTC, irbekrm commented on images/golang-aws/build.yaml
> +
Suggestion: add a variants section and tag the images with the version of Go this is based on like it's done for golang-dind image https://github.com/jetstack/testing/blob/master/images/golang-dind/build.yaml#L8 and parameterize the Go version in the Dockerfile too.

2021-07-30 14:08 UTC, RinkiyaKeDad commented
/release-note-none

2021-08-02 12:01 UTC, jakexks submitted a review, later dismissed
/lgtm

2021-08-02 12:08 UTC, RinkiyaKeDad commented
/test verify

2021-08-02 13:09 UTC, irbekrm commented
/ok-to-test

2021-08-02 13:35 UTC, jakexks commented on images/golang-aws/build.yaml
> +- ${_REGISTRY}/${_NAME}:latest-${GO_VERSION}
```suggestion
- ${_REGISTRY}/${_NAME}:latest
```

Latest is special cased so docker pull without any tag will still work

2021-08-02 13:38 UTC, jakexks commented
/lgtm

2021-08-02 14:41 UTC, jakexks approved these changes

2021-08-02 14:43 UTC, merged