Enable periodic tests for release-1.9 branch
jetstack/testing pull request #701
Opened 2022-06-24 15:38 UTC by SgtCoDFish

This is part of the [release process](https://cert-manager.io/docs/contributing/release-process/):

> (initial alpha only) Create a PR on [jetstack/testing](https://github.com/jetstack/testing), changing the release-next periodic tests interval to 2h, configured in

2022-06-24 16:34 UTC, irbekrm requested changes
Thanks @SgtCoDFish !

I've added  nits for running with SSA enabled on kube 1.22+ apart from that happy to lgtm

2022-06-24 16:34 UTC, irbekrm commented on config/jobs/cert-manager/cert-manager/release-next/cert-manager-release-next-periodics.yaml
> +    preset-enable-all-feature-gates-disable-ssa: "true"
For 1.22 we do want to run SSA tests

2022-06-27 10:31 UTC, SgtCoDFish commented
Thanks @irbekrm good catch! I've added a commit enabling SSA for those tests :grin:

2022-06-27 10:55 UTC, irbekrm commented
Thanks @SgtCoDFish !

/lgtm
/approve

2022-06-27 11:01 UTC, merged